### ISSUE TITLE
Plans for Upaating to 1.1.9.4?

### ISSUE THREAD

**Issue by CloudeLecaw** [Perotins/Blackjack#5]
Are there any plans for an update with the 1.19.4? :-)

**Comment by maximus-f** [comment]
Sure, what doesn't work for 1.19.4? Please let me know, I honestly haven't been keeping up lately.

**Comment by CloudeLecaw** [comment]
Could you do me a favor and check with this config file?

```
#
# BLACKJACK
#      by Perotin


# Set to true if you want this plugin to use vault eco, false if you want it to use exp
cash-or-xp: true
# This is a toggle of whether or not players should be allowed to bet more money than they currently have
bet-overflow: false
# If the above is set to true, this is the max amount they can bet of money theey don't have
bet-overflow-max: 10

# The percentage that should be taxed / deducted from winnings. Set to 0.0 for no taxes. Range is 0.0 to 100.0 .
tax-percent: 0.0

# Minimum amount able to bet and the maximum amount to bet! Setting either to zero will negate it completely.
bet-min: 1.0
bet-max: 30.0

# The following options relate to the move to surrender

# Should surrendering (forfeit the game and keep a % of your bet)
enable-surrender: true

# What percentage of the bet should the server take? (1-99)
surrender-percentage-to-take: 50.0

# Disable the change bet buttons? (Players cannot change their amount in the bet)
enable-change-bet: true

# One user requested this, basically, it'll run the specified command below when each round of blackjack starts. If you want
# to use this, then set the below to 'true' and specify your command.
custom-command: false
command: "/Example $amount$"

# Should there be a multiplier for Blackjack (score of 21)?
enable-multiplier: true

# What should the bet amount be multiplied to for blackjacks?
multiplier: 1.5

# Messages used in plugin
number-or-player: "&cFalsche Befehlsargumente! /blackjack <amount> oder /blackjack <player>"
no-permission: "&cDu hast keine Berechtigung diesnen Befehl zu benutzen."
menu-title: "Blackjack: Einsatz $number$"
blackjack-dealer: "&8&lDealer"
blackjack-win: "&0&lBlack&4&lJack! &7&o($amount$x) "
dealer-lore: "&7&oHit und Stand?"
dealer-cards: "&eDealer Karten ==>"
player-cards: "&eDeine Karten ==>"
unknown-card: "&e???"
incorrect-args: "&cFalsche Befehlsargumente > /blackjack <amount> oder /blackjack <player>"
hit-item: "&eHit"
stand-item: "&eStand"
end-game: "&7Deine Punktzahl: &e$score$ &7Dealer Ergebnis: &e$score2$"
earnings: "&eDeine $result$ $number$ Taler!"
taxxed: "&c-$amount$ besteuert."
won: "Gewonnen"
lost: "Verloren"
tied: "&eUnentschiden, du bekommst deine Taler zurück."
cannot-bet-that-much: "&cSie können nicht mehr Geld setzen, als Sie haben!"
can-only-bet: "&cSie können nur wetten $amount$ über Ihr gesamtes Guthaben!"
tutorial-name: "&eWeiß nicht, wie man spielt Klick mich!"
tutorial:
   - "&eWillkommen zu diesem BlackJack-Tutorial! Zum Abbrechen geben Sie ein &ccancel"
   - "&eDas Ziel des Spiels ist es, eine Punktzahl von 21 zu erreichen, ohne darüber hinauszugehen, und den Dealer mit einer höheren Punktzahl schlagen. "
   - "&eDie Karten 2-10 sind ihren Nennwert wert (4 Pik ist 4))."
   - "&4Könige&e, &4Buben &eund &4Damen &2sind 10 wert. Ein &4Ass &eist 1 oder 11, je nachdem, was für den Spieler besser ist."
   - "&4HIT &eist, wenn Sie eine andere Karte wünschen, aber Sie gehen das Risiko ein, über 21 zu gehen und zu verlieren."
   - "&4Standing &eist, wenn Sie mit Ihren Karten behalten wollen und das Spiel beenden möchten."
   - "&eDanke für das Spielen!" 
bet-max-message: "&cDas Maximum was du setzen kannst $amount$!"
bet-min-message: "&cDas Minimum was du setzen kannst$amount$!"
surrender-item: "&eAufgeben"
surrender-lore: "&7&o(Die Hälfte Ihres Einsatzes wird behalten)"
surrender-message: "&eDu hast aufgegeben und behalten $amount$ von deinen Einsatz $bet$!"

# Session Messages
earnings-gui: "&eEinnahmen des vorherigen Spiels:"
keep-playing: "&aWeiter spielen?"
stop-playing: "&cSitzung beenden?"
total-earnings: "&eGesamteinnahmen: $amount$"
session-ending: "&eNach dem Gewinn von $amount$, hast du nun $$outcome$!"
change-bet-amount: "&eWettbetrag ändern"
your-bet-amount: "&eIhr Einsatzbetrag"
continue-playing: "Willst du weiterspielen, $player$?"

# New messages
blackjack: "&bBLACKJACK"
previous-game: "&7Vorheriges Spiel öffnen. . ."
wins-stat: "&cGewinnt: &f$amount$"
loss-stat: "&cVerliert: &f$amount$"
ratio-stat: "&cW/V Verhältnis: &f$amount$"
amount-added: "&a+$amount$"
amount-subtracted: "&c-$amount$"


# Names of cards
spades: "Piek"
hearts: "Herz"
clubs: "Kreuz"
diamonds: "Karo"
jack: "Bube"
queen: "Königin"
king:  "König"
ace: "Ass"
```
 
With this file i can take out the items of the gui... while this does not happen with the original file

Current Error:
- Sometimes when i start a game and not finish it (ESC) and leaveing the game after, i cant contine playing or make a new game after relog.
- When i set no amount i get this error:
```
[22:55:44 INFO]: Cloude_Lecaw issued server command: /blackjack 1
>....
[22:56:03 INFO]: Cloude_Lecaw issued server command: /blackjack
>....
[22:56:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'blackjack' in plugin Blackjack v1.6.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-499]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-499]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2249) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.server.CancelledPacketHandleException
>....
```

**Comment by CloudeLecaw** [comment]
looks like it is caused because the items are renamed?
Here a video with the differences with renamed items and original config.
https://streamable.com/zmbbm9

**Comment by maximus-f** [comment]
Thanks for the video, I am trying to get into my minecraft account to test but having issues because of microsoft migration. But I am bored so I'll get around to fixing this. Thanks for the quick reply!

**Comment by maximus-f** [comment]
Sorry, I figured out the reason why. Update soon.
